export type CategoryKey = "work" | "time" | "files" | "reuse" | "tools" | "workflow" | "goal";

export const sectionOrder: { key: CategoryKey; label: string }[] = [
  { key: "work", label: "Work" },
  { key: "time", label: "Time" },
  { key: "files", label: "Files" },
  { key: "reuse", label: "Reuse" },
  { key: "tools", label: "Tools" },
  { key: "workflow", label: "Workflow" },
  { key: "goal", label: "Goal" },
];

export type Answers = Record<string, string | string[]>;

export type Question = {
  id: string;
  section: CategoryKey;
  title: string;
  help?: string;
  type: "single" | "multi" | "text" | "longtext";
  options?: string[];
  maxSelect?: number;
  optional?: boolean;
  placeholder?: string;
  showIf?: (answers: Answers) => boolean;
};

const mainProblemIs = (value: string) => (answers: Answers) => answers["main_problem"] === value;

export const questions: Question[] = [
  {
    id: "work_types",
    section: "work",
    title: "What does most of your digital work involve?",
    help: "Select up to 3.",
    type: "multi",
    maxSelect: 3,
    options: [
      "Creating content",
      "Writing",
      "Research",
      "Studying / learning",
      "Client work",
      "Managing projects",
      "Communication / email",
      "Design / editing",
      "Managing information / knowledge",
      "Planning / organization",
      "Coding / technical work",
      "Other",
    ],
  },
  {
    id: "apps",
    section: "work",
    title: "What are the main apps you use every day?",
    help: "List 3 to 7. Example: Chrome, Notion, Obsidian, Claude, DaVinci Resolve",
    type: "text",
    placeholder: "Chrome, Notion, Obsidian, Claude, DaVinci Resolve",
  },
  {
    id: "digital_share",
    section: "work",
    title: "How much of your work happens digitally?",
    type: "single",
    options: ["Almost everything", "Most of it", "About half", "Less than half"],
  },
  {
    id: "problems",
    section: "time",
    title: "Which of these problems do you experience regularly?",
    help: "Select all that apply.",
    type: "multi",
    options: [
      "I repeatedly do things manually that feel like they should be faster",
      "I know I've saved something but can't find it",
      "I keep rebuilding things I've already made",
      "My files are difficult to navigate",
      "My notes and information are scattered",
      "I have too many tools and don't know what each one should be used for",
      "I know my software can probably do more, but I don't know how",
      "I save lots of information but rarely use it again",
      "Every project starts from scratch",
      "I don't have clear processes for recurring work",
      "I lose track of where I left off",
      "I have too much digital clutter",
      "I switch between too many apps or places to get something done",
      "I have trouble staying focused",
    ],
  },
  {
    id: "main_problem",
    section: "time",
    title: "Which ONE of those problems bothers you the most?",
    type: "single",
    options: [
      "Doing things manually / too slowly",
      "Finding things",
      "Rebuilding things",
      "Digital clutter / organization",
      "Scattered information",
      "Not getting enough out of my tools",
      "Too many tools / unclear systems",
      "Starting projects from scratch",
      "Lack of repeatable processes",
      "Losing track of work",
      "Staying focused",
      "Something else",
    ],
  },
  {
    id: "cond_manual",
    section: "time",
    title: "What are 1 to 3 things you do repeatedly that feel unnecessarily slow?",
    type: "longtext",
    showIf: mainProblemIs("Doing things manually / too slowly"),
  },
  {
    id: "cond_finding",
    section: "time",
    title: "What's hardest to find?",
    type: "multi",
    options: [
      "Files",
      "Notes",
      "Assets",
      "Bookmarks",
      "Research",
      "Ideas",
      "Projects",
      "Previous work",
      "Other",
    ],
    showIf: mainProblemIs("Finding things"),
  },
  {
    id: "cond_rebuilding",
    section: "time",
    title: "What do you find yourself recreating most often?",
    type: "multi",
    options: [
      "Documents",
      "Projects",
      "Designs",
      "Videos",
      "Presentations",
      "Emails",
      "Prompts",
      "Research",
      "Folder structures",
      "Other",
    ],
    showIf: mainProblemIs("Rebuilding things"),
  },
  {
    id: "cond_scattered",
    section: "time",
    title: "Where does your information currently live?",
    type: "multi",
    options: [
      "Notion",
      "Obsidian",
      "Apple Notes",
      "Google Docs",
      "OneNote",
      "Browser bookmarks",
      "Email",
      "Local files",
      "Cloud storage",
      "Multiple places with no clear system",
      "Other",
    ],
    showIf: mainProblemIs("Scattered information"),
  },
  {
    id: "cond_tools",
    section: "time",
    title: "Which tool do you most wish you could use better?",
    type: "text",
    showIf: mainProblemIs("Not getting enough out of my tools"),
  },
  {
    id: "cond_scratch",
    section: "time",
    title: "What type of projects do you repeatedly start?",
    type: "text",
    showIf: mainProblemIs("Starting projects from scratch"),
  },
  {
    id: "cond_processes",
    section: "time",
    title: "What recurring process do you wish you had a reliable system for?",
    type: "text",
    showIf: mainProblemIs("Lack of repeatable processes"),
  },
  {
    id: "cond_focus",
    section: "time",
    title: "When do you have the most trouble staying focused?",
    type: "multi",
    options: [
      "Starting work",
      "Working for long periods",
      "Switching between tasks",
      "Working from home",
      "Working online",
      "Managing notifications",
      "Social media / websites",
      "Other",
    ],
    showIf: mainProblemIs("Staying focused"),
  },
  {
    id: "wish",
    section: "time",
    title: "Finish this sentence: \"I wish my digital workflow could...\"",
    type: "longtext",
  },
  {
    id: "find_ease",
    section: "files",
    title: "How easy is it to find something you've previously saved or created?",
    type: "single",
    options: [
      "I can usually find anything immediately",
      "Usually easy, but I occasionally waste time searching",
      "I regularly spend several minutes looking",
      "Finding things is a constant problem",
      "I sometimes give up and recreate it",
    ],
  },
  {
    id: "files_org",
    section: "files",
    title: "How do you currently organize your files?",
    type: "single",
    options: [
      "I have a clear folder structure that works well",
      "I have a structure, but it has become messy",
      "I have several different systems",
      "I mostly organize things as I go",
      "My files are fairly chaotic",
      "I mostly rely on search",
    ],
  },
  {
    id: "notes_system",
    section: "files",
    title: "How do you currently manage notes, ideas, and information?",
    type: "single",
    options: [
      "I have a clear system I trust",
      "I have a system, but it has become messy",
      "I use several different systems",
      "I mostly dump things into one place",
      "I save things wherever is convenient",
      "I don't really have a system",
    ],
  },
  {
    id: "save_behavior",
    section: "files",
    title: "When you find something useful online, what usually happens?",
    type: "single",
    options: [
      "I know exactly where it belongs and how I'll use it",
      "I save it somewhere, but often forget about it",
      "I bookmark / save / screenshot it and rarely return to it",
      "I save it in several different places",
      "I usually don't save it",
      "It depends on what it is",
    ],
  },
  {
    id: "reuse_level",
    section: "reuse",
    title: "How much of your existing work do you reuse?",
    type: "single",
    options: [
      "Almost everything is systemized for reuse",
      "I reuse a lot of templates, assets, or processes",
      "I reuse some things, but inconsistently",
      "I mostly recreate things each time",
      "Almost nothing is deliberately built for reuse",
    ],
  },
  {
    id: "project_start",
    section: "reuse",
    title: "When starting a new project, what usually happens?",
    type: "single",
    options: [
      "I have a clear process and reusable starting template",
      "I copy an old project and modify it",
      "I have a rough process but still figure things out each time",
      "I start from scratch",
      "It depends on the project",
    ],
  },
  {
    id: "project_end",
    section: "reuse",
    title: "When you finish a project, what happens to the things you created?",
    type: "single",
    options: [
      "Everything is properly archived and easy to reuse",
      "I save everything, but organization isn't great",
      "Some things get reused, while others disappear into folders",
      "I usually just move on to the next project",
      "Completed projects mostly become digital clutter",
    ],
  },
  {
    id: "app_discovery",
    section: "tools",
    title:
      "How often do you discover that an app you already use can do something you didn't know about?",
    type: "single",
    options: ["Almost never", "Occasionally", "Pretty often", "Constantly"],
  },
  {
    id: "apps_to_learn",
    section: "tools",
    title: "Which apps do you wish you knew better?",
    help: "Optional.",
    type: "text",
    optional: true,
  },
  {
    id: "repetitive_handling",
    section: "tools",
    title: "How do you currently handle repetitive tasks?",
    type: "single",
    options: [
      "I have shortcuts / templates / systems for most of them",
      "I have systems for some of them",
      "I know I should create systems, but haven't",
      "I mostly do them manually",
      "I haven't really thought about it",
    ],
  },
  {
    id: "task_tools",
    section: "workflow",
    title: "How do you currently manage tasks and projects?",
    help: "Select all that apply.",
    type: "multi",
    options: [
      "Task manager",
      "Calendar",
      "Notes app",
      "Notion",
      "Obsidian",
      "Spreadsheet",
      "Project management software",
      "Email",
      "Paper",
      "I mostly keep things in my head",
      "Other",
    ],
  },
  {
    id: "next_action_freq",
    section: "workflow",
    title: "How often do you have to stop and figure out \"what should I do next?\"",
    type: "single",
    options: ["Almost never", "Occasionally", "A few times a day", "Very often", "Constantly"],
  },
  {
    id: "lose_place_freq",
    section: "workflow",
    title: "How often do you lose your place when switching between projects or tasks?",
    type: "single",
    options: [
      "Almost never",
      "Occasionally",
      "A few times a week",
      "Every day",
      "Multiple times a day",
    ],
  },
  {
    id: "one_thing",
    section: "goal",
    title: "If you could improve ONE thing about the way you work, what would it be?",
    type: "longtext",
  },
  {
    id: "better_outcomes",
    section: "goal",
    title: "What would a noticeably better digital workflow allow you to do?",
    help: "Select up to 3.",
    type: "multi",
    maxSelect: 3,
    options: [
      "Get more work done in the same amount of time",
      "Spend less time on repetitive tasks",
      "Find things instantly",
      "Start projects faster",
      "Reuse more of my previous work",
      "Keep my digital workspace organized",
      "Get more out of my existing apps",
      "Better manage my ideas and information",
      "Reduce the number of small decisions I make",
      "Stay focused more easily",
      "Pick up where I left off more easily",
      "Feel more in control of my digital work",
    ],
  },
  {
    id: "seriousness",
    section: "goal",
    title: "How serious are you about improving your workflow?",
    type: "single",
    options: [
      "I'm just curious",
      "I'd like to improve it eventually",
      "I've been meaning to fix it for a while",
      "I'm actively looking for a better system",
      "I want to fix it now",
    ],
  },
  {
    id: "interest",
    section: "goal",
    title:
      "If I identify clear opportunities to improve your workflow, would you be interested in having me help you implement them?",
    type: "single",
    options: [
      "Yes, that's exactly what I'm looking for",
      "Maybe, I'd like to see what you recommend",
      "I'm mainly interested in the free diagnosis",
    ],
  },
];

export function visibleQuestions(answers: Answers): Question[] {
  return questions.filter((q) => !q.showIf || q.showIf(answers));
}
